@startuml
    Title packlist modèle de données
    class liste {
        - nom : string
        + getNom()
        + setNom()
        + addItem()
    }
    class item {
        - nom : string
        - poids : int
        - packed : boolean
        + getNom()
        + setNom()
        + getPoids()
        + setPoids()
        + isPacked()
        + setPacked()
    }

    liste "1" *-- "*" item

    legend
        new : mise en place des décorateurs de visibilité
    endlegend
@enduml