@startuml
    Title packlist modèle de données
    class liste {
        nom : string
    }
    class item {
        nom : string
        poids : int
        packed : boolean
    }

    liste "1" *-- "*" item

    legend
        new : mise en place des propriétés de classes
    endlegend
@enduml