@startuml
    Title Diagramme d'activité calcul poids empaqueté

    start
        :packedwheight = 0;
        while (il y a des item) is (encore)
            if (cet item a un poids ?) then (oui)
                if (empaqueté ?)  then (oui)
                    : Ajouter poids à packedWeight;
                endif
            else (non)
            endif
        endwhile (fini)
    end
@enduml