@startuml

    title Aide mémoire for (Plant)UML, diagramme de classe

    start

    partition "groupe d'actions" {
        note right : syntaxe : \n partition "groupe" {\n}
        :action simple;
        note right : syntaxe : \n :action simple;
        :entrée (formalisme SDL)<
        note right : syntaxe : \n :action simple<
        :sortie (formalisme SDL)>
        note right : syntaxe : \n :action simple>
    }

    if (un test) then (oui)
      :youpi;
    elseif (un autre test) then (oui)
      :super;
    else (non)
      :sniff;
      stop
    endif
    note right
        syntaxe :
         if (un test) then (oui)
         else (non)
         endif
    end note


    while (toujours vrai?) is (vrai)
      :faire qque chose;
      :puis une autre;
    endwhile (faux)

    note right
        syntaxe :
         while (toujours vrai?)
           :faire qque chose;
           :puis une autre;
         endwhile
    end note

    end


@enduml
