
@startuml
	title My internal model

	!include sample_class_diag_11measure.pu
	hide com.zz.model.measure.OneWifiMeasure

	class com.zz.model.Campaign 
	class com.zz.model.Room 

	com.zz.model.Campaign "1" *-- "many" com.zz.model.Room
	com.zz.model.Room "1" *--  "many" com.zz.model.measure.Measure

	legend
		new : using hide on class
	endlegend
@enduml