
@startuml
	title My internal model


	class com.zz.model.Campaign 
	class com.zz.model.Room 
	package com.zz.model.measure {
		class com.zz.model.measure.Measure {
			mTimestamp
			+ getWifis()
		}
		class com.zz.model.measure.OneWifiMeasure
	}

	com.zz.model.Campaign "1" *-- "many" com.zz.model.Room
	com.zz.model.Room "1" *--  "many" com.zz.model.measure.Measure
	com.zz.model.measure.Measure "1" *--  "many" com.zz.model.measure.OneWifiMeasure


	note "This note is connected\nto several objects." as com.zz.model.Note
	com.zz.model.Room .. com.zz.model.Note
	com.zz.model.Note .. com.zz.model.measure.Measure

	legend
		new : making sub-package
	endlegend
@enduml