
@startuml

	class com.zz.model.Measure {
		mTimestamp
		+ getWifis()
	}
	class com.zz.model.OneWifiMeasure

	com.zz.model.Measure "1" *--  "many" com.zz.model.OneWifiMeasure


	note "This note is connected\nto several objects." as com.zz.model.Note
	com.zz.model.Room .. com.zz.model.Note
	com.zz.model.Note .. com.zz.model.Measure

@enduml