@startuml
title Process running at fragment start

|OptWifiWelcomeFragment|
start
:displayNotYetReadyForTestOnUIThread;
|OptWifiActivity|
:launch retrieval of livebox SSIDS;
if (success) then (yes)
	|OptWifiWelcomeFragment|
	:displayReadyForTestOnUIThread;
else (no)
	:displayFailedPreparingOnUIThread;
endif
end

	legend
		new : adding swimlane
	endlegend
@enduml